config/routes.rb
  Rails.application.routes.draw do

    resources :haunts do
      member do
        post 'upvote'
      end
      resources :comments
    end

  get 'sessions/new'

  get 'users/new'
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'haunts' => 'haunts#index'

 
  resources :users

  resources :microposts,          only: [:create, :destroy]
end

app/models/haunt.rb
class Haunt < ActiveRecord::Base

	geocoded_by :address
	after_validation :geocode
	belongs_to :user
	has_many :comments
	has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb:"150x150#" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	def self.search(search)
  		where("title LIKE ?", "%#{search}%") 
  		where("description LIKE ?", "%#{search}%")
	end
end

app/controllers/haunts_controller.rb
class HauntsController < ApplicationController
  before_action :set_haunt, only: [:show, :edit, :update, :destroy]

  # GET /haunts
  # GET /haunts.json
  def index
    # @haunts = Haunt.all
    if params[:search]
      # @haunts = Haunt.search(params[:search]).order("created_at DESC")
      @haunts = Haunt.find_by_sql("SELECT * FROM haunts WHERE title LIKE '#{params[:search]}' OR description LIKE '#{params[:search]}'")
    else
      @haunts = Haunt.all.order('created_at DESC')
    end
    @users = User.all
    @hash = Gmaps4rails.build_markers(@haunts) do |haunt, marker|
      marker.lat haunt.latitude
      marker.lng haunt.longitude
      marker.infowindow haunt.title 
      marker.picture( {
        "url" => "http://www.imagemagick.org/Usage/images/ghost.gif",
        "width" => 32,
        "height" => 32
        })
      marker.json({ title: haunt.title })
    end
  end

  # GET /haunts/1
  # GET /haunts/1.json
  def show
  end

  # GET /haunts/new
  def new
    @haunt = Haunt.new
    @haunt.user_id = current_user.id
  end

  # GET /haunts/1/edit
  def edit
  end

  # POST /haunts
  # POST /haunts.json
  def create
    @haunt = Haunt.new(haunt_params)

    respond_to do |format|
      if @haunt.save
        format.html { redirect_to @haunt, notice: 'Haunt was successfully created.' }
        format.json { render :show, status: :created, location: @haunt }
      else
        format.html { render :new }
        format.json { render json: @haunt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /haunts/1
  # PATCH/PUT /haunts/1.json
  def update
    respond_to do |format|
      if @haunt.update(haunt_params)
        format.html { redirect_to @haunt, notice: 'Haunt was successfully updated.' }
        format.json { render :show, status: :ok, location: @haunt }
      else
        format.html { render :edit }
        format.json { render json: @haunt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /haunts/1
  # DELETE /haunts/1.json
  def destroy
    @haunt.destroy
    respond_to do |format|
      format.html { redirect_to haunts_url, notice: 'Haunt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @haunt = Haunt.find(params[:id])
    votes = @haunt.votes
    @haunt.update(votes: votes + 1)
    redirect_to(haunts_path)
  end


    # Use callbacks to share common setup or constraints between actions.
    def set_haunt
      @haunt = Haunt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def haunt_params
      params.require(:haunt).permit(:latitude, :longitude, :address, :description, :title, :user_id, :image)
    end
end

app/helpers/haunts_helper.rb
module HauntsHelper
end

app/views/haunts/_form.html.erb
<%= form_for @haunt, html: {multipart: true} do |f| %>
  <% if @haunt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@haunt.errors.count, "error") %> prohibited this haunt from being saved:</h2>

      <ul>
      <% @haunt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :latitude %><p> (optional) </p> <br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %> <p> (optional) </p> <br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class ="field"> 
  <%= f.label :image %> <p> (optional) </p> <br>
  <%= f.file_field :image %> 
  </div>
  <div class = "field">
    <%= f.hidden_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>

app/views/haunts/_haunt.html.erb
<h1> Search Results </h1>

<table>
  <thead>
    <tr>
<!--       <th>Latitude</th>
      <th>Longitude</th> -->
      <th>Address</th>
      <th>Title</th>
      <th> Posted by </th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @haunts.each do |haunt| %>
      <tr>
<!--         <td><%= haunt.latitude %></td>
        <td><%= haunt.longitude %></td> -->
        <td><%= haunt.address %></td>
        <td><%= haunt.title %></td>
        <td><%= haunt.user_id %> </td>
        <td><%= link_to 'Show', haunt %></td>
        <td><%= link_to 'Edit', edit_haunt_path(haunt) %></td>
        <td><%= link_to 'Destroy', haunt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= button_to '+1', upvote_haunt_path(haunt), method: :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/haunts/edit.html.erb
<h1>Editing Haunt</h1>

<%= render 'form' %>

<%= link_to 'Show', @haunt %> |
<%= link_to 'Back', haunts_path %>

app/views/haunts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Haunts</h1>
<p> Search by Title (must match exactly) </p>
<%= form_tag(haunts_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Haunts" %>
<%= submit_tag "Search" %>
<% end %>

<% if @haunts.present? %>
  <%= render 'haunt' %>
<% else %>
  <p>There are no haunts containing the term(s) <%= params[:search] %>.</p>

<% end %>

<br>

<center> <button> <%= link_to 'New Haunt', new_haunt_path %> </button> </center>
<br>


<div style='width: 800px;'>
    <div id="geolocation" style='width: 800px; height: 400px;'></div>
  </div>

<script type="text/javascript">
var mapStyle = [
    {
        "featureType": "all",
        "elementType": "labels.text",
        "stylers": [
            {
                "visibility": "on"
            }
        ]
    },
    {
        "featureType": "all",
        "elementType": "labels.text.fill",
        "stylers": [
            {
                "color": "#ffffff"
            },
            {
                "visibility": "on"
            }
        ]
    },
    {
        "featureType": "all",
        "elementType": "labels.text.stroke",
        "stylers": [
            {
                "visibility": "on"
            },
            {
                "color": "#413c48"
            },
            {
                "weight": "3.40"
            }
        ]
    },
    {
        "featureType": "administrative",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "#6f38c7"
            },
            {
                "lightness": 20
            }
        ]
    },
    {
        "featureType": "administrative",
        "elementType": "geometry.stroke",
        "stylers": [
            {
                "color": "#392855"
            },
            {
                "lightness": 17
            },
            {
                "weight": 1.2
            }
        ]
    },
    {
        "featureType": "administrative.neighborhood",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "on"
            }
        ]
    },
    {
        "featureType": "administrative.land_parcel",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "on"
            },
            {
                "color": "#524070"
            }
        ]
    },
    {
        "featureType": "administrative.land_parcel",
        "elementType": "geometry",
        "stylers": [
            {
                "visibility": "on"
            },
            {
                "color": "#6c3db8"
            }
        ]
    },
    {
        "featureType": "landscape",
        "elementType": "geometry",
        "stylers": [
            {
                "lightness": "25"
            },
            {
                "visibility": "on"
            },
            {
                "color": "#b1a0cb"
            }
        ]
    },
    {
        "featureType": "landscape.man_made",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "on"
            },
            {
                "color": "#8970b1"
            }
        ]
    },
    {
        "featureType": "poi",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#47385f"
            },
            {
                "lightness": 21
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "#d6bcff"
            },
            {
                "lightness": 17
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "geometry.stroke",
        "stylers": [
            {
                "color": "#000000"
            },
            {
                "lightness": 29
            },
            {
                "weight": 0.2
            }
        ]
    },
    {
        "featureType": "road.arterial",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#000000"
            },
            {
                "lightness": 18
            }
        ]
    },
    {
        "featureType": "road.local",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#522697"
            },
            {
                "lightness": 16
            }
        ]
    },
    {
        "featureType": "transit",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#af96d9"
            },
            {
                "lightness": 19
            }
        ]
    },
    {
        "featureType": "water",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#271a3b"
            },
            {
                "lightness": 17
            }
        ]
    },
    {
        "featureType": "water",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "#0f071b"
            }
        ]
    }
];
var handler = Gmaps.build('Google');
handler.buildMap( { provider: {
  styles: mapStyle
}, internal: {id: 'geolocation'} }, function(){
    markers = handler.addMarkers(<%= raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  // if(navigator.geolocation)
  //   navigator.geolocation.getCurrentPosition(displayOnMap);
});
function displayOnMap(position){
  var marker = handler.addMarker({
    lat: position.coords.latitude,
    lng: position.coords.longitude
  });
  handler.map.centerOn(marker);
};
// handler = Gmaps.build('Google');
// handler.buildMap({ provider: {
//   styles: mapStyle
// }, internal: {id: 'custom_style'}}, function(){
//   markers = handler.addMarkers(<%= raw @hash.to_json %>);
//   handler.bounds.extendWith(markers);
//   handler.fitMapToBounds();
// });
</script>

app/views/haunts/new.html.erb
<h1>New Haunt</h1>

<%= render 'form' %>

<%= link_to 'Back', haunts_path %>

app/views/haunts/show.html.erb
<p id="notice"><%= notice %></p>

<p> <center>
  <strong>Title:</strong>
  <%= @haunt.title %>
</p>

<p> <center> 
<%= image_tag@haunt.image.url(:medium)%>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @haunt.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @haunt.longitude %>
</p>

<p>
  <strong>Address:</strong>
  <%= @haunt.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @haunt.description %>
</p>

<p>
  <strong>Posted by:</strong>
  <a href="/users/<%= @haunt.user_id %>"><%= @haunt.user.name %></a>
</p>

<h2>Comments</h2>
<% @haunt.comments.each do |comment| %>
  <p>
    <b>Commenter:</b>
    <%= comment.commenter %>
  </p>
 
  <p>
    <b>Comment:</b>
    <%= comment.body %>
  </p>
<% end %>


<h2>Add a comment:</h2>
<%= render "comments/form" %>

<%= link_to 'Edit', edit_haunt_path(@haunt) %> |
<%= link_to 'Back', haunts_path %>
<br>